# Generated by Django 6.0.6 on 2026-06-30 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('project_type', models.CharField(choices=[('scratch', 'Scratch Master'), ('python', 'Python Coder')], default='scratch', max_length=10, verbose_name='Education Type')),
                ('description', models.TextField(verbose_name="Student's Project Description")),
                ('scratch_embed_url', models.URLField(blank=True, null=True, verbose_name='Scratch Embed/Paylaşım Linki')),
                ('python_project_url', models.URLField(blank=True, null=True, verbose_name='Python Proje/İndirme Linki')),
            ],
            options={
                'verbose_name': 'Student Project',
                'verbose_name_plural': 'Student Projects',
            },
        ),
    ]
