# Generated by Django 6.0.6 on 2026-07-01 20:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0003_studentproject_student'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Doğum Tarihi')),
                ('parent_phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Veli Telefonu')),
                ('school_grade', models.CharField(blank=True, max_length=20, null=True, verbose_name='Okul Sınıfı / Yaş Grubu')),
                ('teacher_notes', models.TextField(blank=True, null=True, verbose_name='Öğretmen Özel Notları')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
        ),
    ]
