# Generated by Django 6.0.6 on 2026-07-01 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0004_studentprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentproject',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='studentproject',
            name='last_name',
        ),
    ]
