# Generated by Django 6.0.6 on 2026-07-01 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0005_remove_studentproject_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='badges',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Kazanılan Rozetler (Virgülle ayırın)'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='exp',
            field=models.IntegerField(default=0, verbose_name='Deneyim Puanı (EXP)'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='level',
            field=models.IntegerField(default=1, verbose_name='Seviye (Level)'),
        ),
    ]
