# Generated by Django 6.0.6 on 2026-07-01 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0006_studentprofile_badges_studentprofile_exp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/', verbose_name='Profil Fotoğrafı'),
        ),
    ]
