# Generated by Django 6.0.6 on 2026-07-02 09:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0008_studentproject_like_count_studentproject_liked_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Rozet Kodu')),
                ('title', models.CharField(max_length=100, verbose_name='Rozet Adı')),
                ('description', models.TextField(verbose_name='Kazanma Koşulu')),
                ('icon_class', models.CharField(default='fa-award', max_length=50, verbose_name='FontAwesome İkon Sınıfı')),
                ('badge_color', models.CharField(default='#3B82F6', max_length=20, verbose_name='Rozet Rengi (Hex)')),
            ],
        ),
        migrations.AddField(
            model_name='studentproject',
            name='is_creative_design',
            field=models.BooleanField(default=False, verbose_name='Öğretmen Onayı: Yaratıcı Tasarım'),
        ),
        migrations.AddField(
            model_name='studentproject',
            name='is_original_idea',
            field=models.BooleanField(default=False, verbose_name='Öğretmen Onayı: Özgün Fikir'),
        ),
        migrations.CreateModel(
            name='StudentBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Kazanılma Tarihi')),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='showcase.badge')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earned_badges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('student', 'badge')},
            },
        ),
    ]
