# Generated by Django 6.0.6 on 2026-07-02 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0009_badge_studentproject_is_creative_design_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='badges',
        ),
    ]
