# Generated by Django 6.0.6 on 2026-07-02 19:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0010_remove_studentprofile_badges'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='badge_color',
            field=models.CharField(default='#3B82F6', max_length=20, verbose_name='Color Identity (Hexadecimal Representation)'),
        ),
        migrations.AlterField(
            model_name='badge',
            name='code',
            field=models.CharField(max_length=50, unique=True, verbose_name='Internal Unique Identity Code'),
        ),
        migrations.AlterField(
            model_name='badge',
            name='description',
            field=models.TextField(verbose_name='Target Requirement Criteria'),
        ),
        migrations.AlterField(
            model_name='badge',
            name='icon_class',
            field=models.CharField(default='fa-award', max_length=50, verbose_name='FontAwesome Presentation Tag Style Class'),
        ),
        migrations.AlterField(
            model_name='badge',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Badge Moniker / Public Name'),
        ),
        migrations.AlterField(
            model_name='studentbadge',
            name='badge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='showcase.badge', verbose_name='Acquired Award Blueprint'),
        ),
        migrations.AlterField(
            model_name='studentbadge',
            name='earned_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Historical Achievement Timestamp'),
        ),
        migrations.AlterField(
            model_name='studentbadge',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earned_badges', to=settings.AUTH_USER_MODEL, verbose_name='Recipient Student'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='exp',
            field=models.IntegerField(default=0, verbose_name='Total Experience Points (EXP)'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='level',
            field=models.IntegerField(default=1, verbose_name='Current Level'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='parent_phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Parent Contact Number'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/', verbose_name='Avatar / Profile Image'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='school_grade',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='School Grade / Age Group'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='teacher_notes',
            field=models.TextField(blank=True, null=True, verbose_name="Teacher's Internal Notes"),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='User Account'),
        ),
        migrations.AlterField(
            model_name='studentproject',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='project_covers/', verbose_name='Showcase Thumbnail'),
        ),
        migrations.AlterField(
            model_name='studentproject',
            name='description',
            field=models.TextField(verbose_name='Project Narrative & Overview'),
        ),
        migrations.AlterField(
            model_name='studentproject',
            name='is_creative_design',
            field=models.BooleanField(default=False, verbose_name='Instructor Verification: Aesthetic Excellence'),
        ),
        migrations.AlterField(
            model_name='studentproject',
            name='is_original_idea',
            field=models.BooleanField(default=False, verbose_name='Instructor Verification: Elite Innovation'),
        ),
        migrations.AlterField(
            model_name='studentproject',
            name='like_count',
            field=models.IntegerField(default=0, verbose_name='Cached Performance Counter'),
        ),
        migrations.AlterField(
            model_name='studentproject',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='liked_projects', to=settings.AUTH_USER_MODEL, verbose_name='Subscribed Patrons'),
        ),
        migrations.AlterField(
            model_name='studentproject',
            name='project_type',
            field=models.CharField(choices=[('scratch', 'Scratch Master'), ('python', 'Python Coder')], default='scratch', max_length=10, verbose_name='Framework / Track Type'),
        ),
        migrations.AlterField(
            model_name='studentproject',
            name='python_project_url',
            field=models.URLField(blank=True, null=True, verbose_name='Python Repository / Source Code Download URL'),
        ),
        migrations.AlterField(
            model_name='studentproject',
            name='scratch_embed_url',
            field=models.URLField(blank=True, null=True, verbose_name='Scratch Sandbox Embed URL'),
        ),
        migrations.AlterField(
            model_name='studentproject',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL, verbose_name='Student Author'),
        ),
    ]
