# Generated by Django 6.0.6 on 2026-07-30 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0011_alter_badge_badge_color_alter_badge_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentproject',
            name='title',
            field=models.CharField(default='Proje', max_length=200, verbose_name='Project Title'),
            preserve_default=False,
        ),
    ]
