# Generated by Django 6.0.6 on 2026-08-22 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0012_studentproject_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='level',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='parent_phone',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='profile_image',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='school_grade',
        ),
    ]
