# Generated by Django 6.0.6 on 2026-08-20 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('message', models.TextField(verbose_name='Message')),
                ('announcement_type', models.CharField(choices=[('general', 'General'), ('contest', 'Contest'), ('homework', 'Homework'), ('event', 'Event'), ('system', 'System')], default='general', max_length=20, verbose_name='Announcement Type')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('is_popup', models.BooleanField(default=True, verbose_name='Show as Popup')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Expiration Date')),
            ],
            options={
                'verbose_name': 'Announcement',
                'verbose_name_plural': 'Announcements',
                'ordering': ['-created_at'],
            },
        ),
    ]
