# Generated by Django 6.0.6 on 2026-08-20 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='redirect_url',
            field=models.CharField(blank=True, max_length=500, verbose_name='Redirect URL'),
        ),
    ]
