# Generated by Django 6.0.6 on 2026-08-14 16:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Competition Title')),
                ('end_date', models.DateTimeField(verbose_name='Expiration Timestamp (Countdown Target)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active Event')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Competition Event',
                'verbose_name_plural': 'Competition Events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DesignSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Design Title')),
                ('image', models.ImageField(upload_to='competition_designs/', verbose_name='Design Asset File')),
                ('description', models.TextField(blank=True, verbose_name='Design Narrative / Overview')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='contests.competition', verbose_name='Associated Competition')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='design_submissions', to=settings.AUTH_USER_MODEL, verbose_name='Student Creator')),
                ('voters', models.ManyToManyField(blank=True, related_name='voted_designs', to=settings.AUTH_USER_MODEL, verbose_name='Registered Voters')),
            ],
            options={
                'verbose_name': 'Design Submission',
                'verbose_name_plural': 'Design Submissions',
                'ordering': ['-created_at'],
            },
        ),
    ]
