# Generated by Django 6.0.6 on 2026-08-20 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='designsubmission',
            name='description',
        ),
        migrations.RemoveField(
            model_name='designsubmission',
            name='title',
        ),
    ]
