# Generated by Django 6.0.6 on 2026-08-20 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0002_remove_designsubmission_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='designsubmission',
            name='image',
        ),
        migrations.AddField(
            model_name='designsubmission',
            name='image_url',
            field=models.URLField(default='[https://example.com/placeholder.svg](https://example.com/placeholder.svg)', max_length=1000, verbose_name='Design SVG URL'),
            preserve_default=False,
        ),
    ]
